INSERT INTO products (name, description, price, quantity, category, status) VALUES
('Premium Hair Shampoo', 'Moisturizing shampoo for all hair types', 24.99, 50, 'Hair Care', 'active'),
('Professional Hair Dryer', '2000W ionic hair dryer with 3 heat settings', 89.99, 30, 'Styling Tools', 'active'),
('Ceramic Flat Iron', '1-inch ceramic flat iron with adjustable temperature', 59.99, 25, 'Styling Tools', 'active'),
('Hair Color Kit', 'Professional hair color kit with developer', 34.99, 40, 'Hair Color', 'active'),
('Deep Conditioner', 'Intensive hair treatment for damaged hair', 29.99, 35, 'Hair Care', 'active'),
('Hair Spray', 'Strong hold hair spray with UV protection', 19.99, 45, 'Styling Products', 'active'),
('Curling Wand', '1.25-inch curling wand with heat protection glove', 49.99, 20, 'Styling Tools', 'active'),
('Hair Mask', 'Repairing hair mask with keratin', 39.99, 30, 'Hair Care', 'active'),
('Hair Brushes Set', 'Professional brush set with 5 different brushes', 44.99, 15, 'Styling Tools', 'active'),
('Hair Clips', 'Set of 12 professional hair clips', 14.99, 60, 'Accessories', 'active'),
('Hair Extensions', '100% human hair extensions, 20 inches', 199.99, 10, 'Hair Extensions', 'active'),
('Hair Wax', 'Strong hold hair wax with matte finish', 22.99, 25, 'Styling Products', 'active'),
('Hair Mousse', 'Volumizing mousse for fine hair', 18.99, 40, 'Styling Products', 'active'),
('Hair Gel', 'Maximum hold hair gel with shine', 16.99, 35, 'Styling Products', 'active'),
('Hair Serum', 'Smoothing serum with argan oil', 27.99, 30, 'Hair Care', 'active'),
('Hair Clippers', 'Professional hair clippers with multiple guards', 79.99, 15, 'Styling Tools', 'active'),
('Hair Ties', 'Set of 50 professional hair ties', 9.99, 100, 'Accessories', 'active'),
('Hair Pins', 'Set of 100 bobby pins', 12.99, 80, 'Accessories', 'active'),
('Hair Comb', 'Professional wide-tooth comb', 8.99, 50, 'Styling Tools', 'active'),
('Hair Scissors', 'Professional hair cutting scissors', 69.99, 10, 'Styling Tools', 'active'),
('Hair Toner', 'Professional hair toner for color correction', 24.99, 25, 'Hair Color', 'active'),
('Hair Bleach', 'Professional hair bleach powder', 19.99, 30, 'Hair Color', 'active'),
('Hair Developer', '40 volume hair developer', 14.99, 40, 'Hair Color', 'active'),
('Hair Gloves', 'Set of 100 disposable hair coloring gloves', 12.99, 20, 'Accessories', 'active'),
('Hair Capes', 'Professional hair cutting capes', 24.99, 15, 'Accessories', 'active'),
('Hair Foils', 'Professional hair foils for highlights', 19.99, 30, 'Accessories', 'active'),
('Hair Bowl', 'Professional mixing bowl for hair color', 9.99, 20, 'Accessories', 'active'),
('Hair Brush', 'Professional round brush for blowouts', 29.99, 25, 'Styling Tools', 'active'),
('Hair Dryer Stand', 'Professional hair dryer stand', 34.99, 15, 'Accessories', 'active'),
('Hair Mirror', 'Professional salon mirror', 89.99, 10, 'Accessories', 'active'),
('Hair Chair', 'Professional salon chair', 299.99, 5, 'Furniture', 'active'),
('Hair Station', 'Professional styling station', 199.99, 8, 'Furniture', 'active'),
('Hair Sink', 'Professional shampoo sink', 399.99, 3, 'Furniture', 'active'),
('Hair Trolley', 'Professional styling trolley', 149.99, 6, 'Furniture', 'active'),
('Hair Cabinet', 'Professional storage cabinet', 249.99, 4, 'Furniture', 'active'),
('Hair Styling Chair', 'Professional styling chair with wheels', 179.99, 7, 'Furniture', 'active'),
('Hair Dryer', 'Professional hair dryer with diffuser', 129.99, 12, 'Styling Tools', 'active'),
('Hair Curler', 'Professional curling iron set', 89.99, 15, 'Styling Tools', 'active'),
('Hair Straightener', 'Professional flat iron with ceramic plates', 79.99, 18, 'Styling Tools', 'active'),
('Hair Trimmer', 'Professional hair trimmer set', 69.99, 10, 'Styling Tools', 'active'),
('Hair Shears', 'Professional hair cutting shears', 99.99, 8, 'Styling Tools', 'active'),
('Hair Razor', 'Professional hair razor with blades', 24.99, 20, 'Styling Tools', 'active'),
('Hair Thinning Shears', 'Professional thinning shears', 59.99, 12, 'Styling Tools', 'active'),
('Hair Texturizer', 'Professional texturizing spray', 19.99, 30, 'Styling Products', 'active'),
('Hair Pomade', 'Professional styling pomade', 22.99, 25, 'Styling Products', 'active'),
('Hair Clay', 'Professional styling clay', 24.99, 20, 'Styling Products', 'active'),
('Hair Paste', 'Professional styling paste', 21.99, 22, 'Styling Products', 'active'),
('Hair Cream', 'Professional styling cream', 23.99, 28, 'Styling Products', 'active'),
('Hair Oil', 'Professional hair oil treatment', 29.99, 25, 'Hair Care', 'active'),
('Hair Mask', 'Professional deep conditioning mask', 34.99, 20, 'Hair Care', 'active'),
('Hair Treatment', 'Professional keratin treatment', 49.99, 15, 'Hair Care', 'active'); 